'0': OK
'1': NEXT without FOR
'2': Variable not found
'3': Subscript wrong
'4': Out of Memory
'5': Out of screen
'6': Number too big
'7': RETURN without GO SUB
'8': End of file
'9': STOP statement
A: Invalid Argument
B: Integer out of range
C: Nonsense in BASIC
D: BREAK
E: Out of DATA
F: Invalid file name
G: No room for line
H: STOP in INPUT
I: FOR without NEXT
J: Invalid I/O device
K: Invalid colour
L: BREAK into program
M: RAMTOP no good
N: Statement lost
O: Invalid stream
P: FN without DEF
Q: Parameter error
R: Tape loading error
